### ISSUE TITLE
AM NRSC-5 

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#33]
Would it be possible to add support for the AM Broadcast band? From what I understand the sidebands are much more narrow and use much higher order modulation.

**Comment by argilo** [comment]
To start, we'd need a good recording of an AM broadcast. Do you have any local stations?

**Comment by pclov3r** [comment]
Unfortunately, I don't.

I can get a station via skip that is around 400 miles away but the sidebands do have fading.  Due to the higher order modulation this may not work well.

**Comment by argilo** [comment]
Well, a recording with some fading is better than no recording at all. If you can capture a couple minutes of RF and post it somewhere, that would definitely help.

**Comment by pclov3r** [comment]
Actually, The Signal ID wiki has a I/Q recording http://www.sigidwiki.com/wiki/File:AM_HD_Radio_iBiquity.zip

It does appear to be a weaker SNR but stable and may work.

**Comment by argilo** [comment]
That could be useful as a starting point. Having a longer recording would still be helpful, as that one is only 14 seconds.

**Comment by argilo** [comment]
In the sigidwiki sample, the digital sidebands are only 7-8 dB above the noise floor, which I expect is much too low for the signal to be decoded. We'll need a much better recording to work with.

**Comment by pclov3r** [comment]
That's what I figured. Hopefully I can find a better sample or somebody can create a better sample.

**Comment by billybobgot** [comment]
Here is a 2 minute recording of my local station in DFW 1.080 MHz
https://drive.google.com/open?id=0B3IrMfVr0MxqazNyelZRLVY5Q1E
Recorded at 16 bit using SDR Console v2.3 build 2760
Was using my Sdr play RSP1
Message me if you need anything

**Comment by argilo** [comment]
Thanks @billybobgot! That looks like a great recording. When I get some time, I'll take a shot at decoding it.

**Comment by pclov3r** [comment]
@argilo Curious if you're had any time or got anywhere with this?

Thanks!

**Comment by argilo** [comment]
As it happens, I'm playing with this right now. But layer 1 AM is quite different from layer 1 FM, so I expect it will be a while until I get it sorted out.

**Comment by pclov3r** [comment]
Have you managed to figure out anything for this over the past month or so? 

Thanks!

**Comment by argilo** [comment]
Unfortunately I haven't made much progress yet. Most of my free time in the past month was spent building an NRSC-5 transmitter: https://github.com/argilo/gr-nrsc5

I'll probably get back to AM eventually, but I can't promise when.

**Comment by pclov3r** [comment]
@argilo Did you ever make any progress with this? 

I'd be willing to help test tho it would require a MW/HF up-converter for use with a RTL-SDR.

**Comment by argilo** [comment]
Unfortunately I haven't made any progress yet. I'll let you know if I do.

**Comment by pclov3r** [comment]
Is there still any plans to have AMBC NRSC-5 support? 

Now, This would require a modded RTl-SDR or a pre-modded SDR that can do direct sampling or a upconverter that would require a frequency offset. Also, Support for RTL-SDR's that can use a Bias-T would be good idea people that use loop antennas. 

Seems like it would require some extra work would be required to implement this well enough for people to use.

**Comment by argilo** [comment]
I would still like to add AM support.

I made an attempt to add AM support to gr-nrsc5 (https://github.com/argilo/gr-nrsc5/compare/add-am) and was able to get the PIDS (station metadata) channel working, but I'm still stuck trying to get the P1 & P3 (audio) channels going. A couple things in the standard are unclear, so it might help to go in the other direction and decode a real signal to see exactly how the data is encoded.

**Comment by argilo** [comment]
I finally got transmit working: https://github.com/argilo/gr-nrsc5/commit/48c2e59e843c390af352dbe9916a050e8528d0e8

I've started working on receive as well, but there's still a fair bit of work left because AM NRSC5 differs from FM in a lot of ways.

**Comment by argilo** [comment]
The code and receiver design are quite messy at the moment, but I've at least managed to get far enough to decode PIDS:

https://github.com/theori-io/nrsc5/compare/master...argilo:add-am

```
23:53:01 Block @ 30
23:53:01 Sync!
23:53:01 Country: US, FCC facility ID: 59820
23:53:01 Station name: KRLD
23:53:01 Country: US, FCC facility ID: 59820
23:53:01 Station name: KRLD
23:53:01 Audio program 0: public, type: None, sound experience 0
23:53:01 Country: US, FCC facility ID: 59820
23:53:01 Station name: KRLD
23:53:01 Station location: 39.956055, -91.363403, 192m
23:53:01 Audio program 0: public, type: None, sound experience 0
23:53:01 Country: US, FCC facility ID: 59820
23:53:01 Station name: KRLD
23:53:01 Slogan: NewsRadio1080 KRLD
23:53:01 Station location: 39.956055, -91.363403, 192m
23:53:01 Audio program 0: public, type: None, sound experience 0
23:53:01 Country: US, FCC facility ID: 59820
23:53:01 Station name: KRLD
23:53:01 Slogan: NewsRadio1080 KRLD
23:53:01 Message: NewsRadio1080 KRLD
23:53:01 Station location: 39.956055, -91.363403, 192m
23:53:01 Audio program 0: public, type: None, sound experience 0
```

**Comment by pclov3r** [comment]
Some nice progress. Looks like you got Audio working now yay!

Any ideas for features and things supported for AMBC? I figure to give best coverage support of a HF upconverter and direct sampling needs to be supported. Also an option to enable the Bias-T for people using loop antennas.

**Comment by argilo** [comment]
Yes indeed, today I finally got to the point where audio decoding works. That said, there's a lot of things that still need to be improved. Here's my to-do list:

- [ ] Add CFO detection. Without it, the receiver won't lock unless the SDR is tuned within 90 Hz of the correct frequency.
- [ ] Decode the audio packets in the "Enhanced" audio stream. This will improve audio quality (20 kbps → 36 kbps).
- [ ] Implement k=9 convolutional decoders for SSE & NEON, or modify the code to always use the generic convolutional decoder when k=9. Currently the code does not compile if the `-DUSE_SSE=ON` or `-DUSE_NEON=ON` flags are used.
- [ ] Improve the multi-stage decimator. The AM receiver currently uses a cascade of five fixed-point decimators, and each one has a gain of two. The input needs to be attenuated to compensate for the gain of the decimators, which reduces the dynamic range. Either the decimators could be changed to unity gain, or they could be replaced with a floating-point implementation.
- [ ] Improve synchronization, in particular by adding per-subchannel tracking loops to average out noise in the training/pilot symbols.
- [ ] Replace magic numbers with named constants.
- [ ] Implement automatic gain control.

**Comment by argilo** [comment]
If anyone has a local station, I would appreciate additional I/Q recordings. All I have to work with at the moment is @billybobgot's recording, and it seems to have some AGC artifacts (visible as vertical bands) which makes decoding a challenge:

![Screenshot from 2020-08-02 23-13-53](https://user-images.githubusercontent.com/583749/89142710-2aa9f680-d516-11ea-8f74-152a85114937.png)

**Comment by argilo** [comment]
I'd especially love a recording of WWFD (Frederick, Maryland), which broadcasts in the all-digital format: https://en.wikipedia.org/wiki/WWFD.

**Comment by pclov3r** [comment]
Does the recording need to be 8-bit or is 16-bit okay?

**Comment by argilo** [comment]
16-bit would be best. I can easily convert to whatever format I need with GNU Radio.

**Comment by pclov3r** [comment]
I am able to get a few HD AMBC stations during the night but i don't think this would be of use to you since they are received via skip and not local groundwave propagation and have lots of selective frequency fading.

**Comment by argilo** [comment]
AM NRSC-5 should be somewhat tolerant of frequency-selective fading since it uses OFDM. Also, there are gaps at ±10 kHz where no OFDM data carriers are used, thereby avoiding interference from adjacent AM carriers. But the required signal-to-noise ratio is relatively high, so I expect reception via skip to be difficult. It might be possible when the primary sidebands are >20 dB above the noise.

**Comment by pclov3r** [comment]
Yeah, I can look tonight to see how the signals actually are.

Would you mind sharing how to convert a 16-bit I/Q file from another program for use with the NRSC5 application using GNUradio for both AM and FM? I looked at it doing it in the past and wasn't sure exactly how to do it and scale things?. Might be useful for others as well. 

My DSP knowledge is severely lacking here :)

**Comment by argilo** [comment]
I used the following GNU Radio 3.8 flow graph to convert @billybobgot's recording to the right format:

![Screenshot from 2020-08-03 22-55-14](https://user-images.githubusercontent.com/583749/89247934-70c98d80-d5dc-11ea-978c-045b17a8e42f.png)

This lowers the frequency by 30 kHz so that the target signal is at 0 Hz, resamples it from 500,000 to 1,488,375 samples per second and writes out 8-bit complex unsigned samples. 

Here's the .grc file:
```
options:
  parameters:
    author: ''
    category: '[GRC Hier Blocks]'
    cmake_opt: ''
    comment: ''
    copyright: ''
    description: ''
    gen_cmake: 'On'
    gen_linking: dynamic
    generate_options: no_gui
    hier_block_src_path: '.:'
    id: am_hd_convert
    max_nouts: '0'
    output_language: python
    placement: (0,0)
    qt_qss_theme: ''
    realtime_scheduling: ''
    run: 'True'
    run_command: '{python} -u {filename}'
    run_options: run
    sizing_mode: fixed
    thread_safe_setters: ''
    title: Not titled yet
    window_size: ''
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [8, 12.0]
    rotation: 0
    state: enabled

blocks:
- name: samp_rate
  id: variable
  parameters:
    comment: ''
    value: '500000'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [200, 12.0]
    rotation: 0
    state: enabled
- name: blocks_add_const_vxx_0_0
  id: blocks_add_const_vxx
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    const: '127.5'
    maxoutbuf: '0'
    minoutbuf: '0'
    type: float
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [640, 236.0]
    rotation: 180
    state: enabled
- name: blocks_complex_to_float_0
  id: blocks_complex_to_float
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [984, 224.0]
    rotation: 180
    state: enabled
- name: blocks_file_sink_0
  id: blocks_file_sink
  parameters:
    affinity: ''
    alias: ''
    append: 'False'
    comment: ''
    file: am-hd.cu8
    type: byte
    unbuffered: 'False'
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [224, 220.0]
    rotation: 180
    state: enabled
- name: blocks_float_to_complex_0
  id: blocks_float_to_complex
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [232, 120.0]
    rotation: 0
    state: enabled
- name: blocks_float_to_uchar_0
  id: blocks_float_to_uchar
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [440, 240.0]
    rotation: 180
    state: enabled
- name: blocks_interleave_0
  id: blocks_interleave
  parameters:
    affinity: ''
    alias: ''
    blocksize: '1'
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    num_streams: '2'
    type: float
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [816, 224.0]
    rotation: 180
    state: enabled
- name: blocks_multiply_const_vxx_0
  id: blocks_multiply_const_vxx
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    const: '3300'
    maxoutbuf: '0'
    minoutbuf: '0'
    type: complex
    vlen: '1'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [632, 132.0]
    rotation: 0
    state: enabled
- name: blocks_rotator_cc_0
  id: blocks_rotator_cc
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    maxoutbuf: '0'
    minoutbuf: '0'
    phase_inc: -30000 * 2 * math.pi / samp_rate
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [408, 132.0]
    rotation: 0
    state: enabled
- name: blocks_wavfile_source_0
  id: blocks_wavfile_source
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    file: 21-Jul-2017 215201.977 1.050MHz 000.wav
    maxoutbuf: '0'
    minoutbuf: '0'
    nchan: '2'
    repeat: 'False'
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [16, 120.0]
    rotation: 0
    state: enabled
- name: import_0
  id: import
  parameters:
    alias: ''
    comment: ''
    imports: import math
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [288, 12.0]
    rotation: 0
    state: enabled
- name: rational_resampler_xxx_0
  id: rational_resampler_xxx
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    decim: '128'
    fbw: '0'
    interp: '147'
    maxoutbuf: '0'
    minoutbuf: '0'
    taps: ''
    type: ccc
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [792, 108.0]
    rotation: 0
    state: enabled
- name: rational_resampler_xxx_1
  id: rational_resampler_xxx
  parameters:
    affinity: ''
    alias: ''
    comment: ''
    decim: '125'
    fbw: '0'
    interp: 81*4
    maxoutbuf: '0'
    minoutbuf: '0'
    taps: ''
    type: ccc
  states:
    bus_sink: false
    bus_source: false
    bus_structure: null
    coordinate: [976, 108.0]
    rotation: 0
    state: enabled

connections:
- [blocks_add_const_vxx_0_0, '0', blocks_float_to_uchar_0, '0']
- [blocks_complex_to_float_0, '0', blocks_interleave_0, '0']
- [blocks_complex_to_float_0, '1', blocks_interleave_0, '1']
- [blocks_float_to_complex_0, '0', blocks_rotator_cc_0, '0']
- [blocks_float_to_uchar_0, '0', blocks_file_sink_0, '0']
- [blocks_interleave_0, '0', blocks_add_const_vxx_0_0, '0']
- [blocks_multiply_const_vxx_0, '0', rational_resampler_xxx_0, '0']
- [blocks_rotator_cc_0, '0', blocks_multiply_const_vxx_0, '0']
- [blocks_wavfile_source_0, '0', blocks_float_to_complex_0, '0']
- [blocks_wavfile_source_0, '1', blocks_float_to_complex_0, '1']
- [rational_resampler_xxx_0, '0', rational_resampler_xxx_1, '0']
- [rational_resampler_xxx_1, '0', blocks_complex_to_float_0, '0']

metadata:
  file_format: 1
```
